include:
  - .gitlab-ci/.defaults.yml


stages:
  - Postprocessing


.docker-push-manifest:
  script:
    - docker pull ${IMAGE_CI_AMD64}
    - docker pull ${IMAGE_CI_ARM64}
    - docker tag ${IMAGE_CI_AMD64} ${IMAGE}-amd64
    - docker tag ${IMAGE_CI_ARM64} ${IMAGE}-arm64
    - docker push ${IMAGE}-amd64
    - docker push ${IMAGE}-arm64
    - docker manifest create ${IMAGE} --amend ${IMAGE}-amd64 --amend ${IMAGE}-arm64
    - docker manifest create ${TAGGED_IMAGE} --amend ${IMAGE}-amd64 --amend ${IMAGE}-arm64
    - docker manifest push ${IMAGE}
    - docker manifest push ${TAGGED_IMAGE}


manifest-cuda:
  stage: Postprocessing
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - !reference [.docker-push-manifest, script]
  variables:
    IMAGE_CI_AMD64: ${IMAGE_BASE_CI}/ros2-cuda:${CI_COMMIT_REF_SLUG}_jazzy-ros-base_ci-amd64
    IMAGE_CI_ARM64: ${IMAGE_BASE_CI}/ros2-cuda:${CI_COMMIT_REF_SLUG}_jazzy-ros-base_ci-arm64
    IMAGE:          ${IMAGE_BASE}/ros2-cuda:jazzy-ros-base
    TAGGED_IMAGE:   ${IMAGE}-v${CI_COMMIT_TAG}

manifest-tensorrt:
  stage: Postprocessing
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - !reference [.docker-push-manifest, script]
  variables:
    IMAGE_CI_AMD64: ${IMAGE_BASE_CI}/ros2-tensorrt:${CI_COMMIT_REF_SLUG}_jazzy-ros-base_ci-amd64
    IMAGE_CI_ARM64: ${IMAGE_BASE_CI}/ros2-tensorrt:${CI_COMMIT_REF_SLUG}_jazzy-ros-base_ci-arm64
    IMAGE:          ${IMAGE_BASE}/ros2-tensorrt:jazzy-ros-base
    TAGGED_IMAGE:   ${IMAGE}-v${CI_COMMIT_TAG}

manifest-torch:
  stage: Postprocessing
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - !reference [.docker-push-manifest, script]
  variables:
    IMAGE_CI_AMD64: ${IMAGE_BASE_CI}/ros2-torch:${CI_COMMIT_REF_SLUG}_jazzy-ros-base-torch2.5.0_ci-amd64
    IMAGE_CI_ARM64: ${IMAGE_BASE_CI}/ros2-torch:${CI_COMMIT_REF_SLUG}_jazzy-ros-base-torch2.5.0_ci-arm64
    IMAGE:          ${IMAGE_BASE}/ros2-torch:jazzy-ros-base-torch2.5.0
    TAGGED_IMAGE:   ${IMAGE}-v${CI_COMMIT_TAG}

manifest-tf:
  stage: Postprocessing
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - !reference [.docker-push-manifest, script]
  variables:
    IMAGE_CI_AMD64: ${IMAGE_BASE_CI}/ros2-tf:${CI_COMMIT_REF_SLUG}_jazzy-ros-base-tf2.18.0_ci-amd64
    IMAGE_CI_ARM64: ${IMAGE_BASE_CI}/ros2-tf:${CI_COMMIT_REF_SLUG}_jazzy-ros-base-tf2.18.0_ci-arm64
    IMAGE:          ${IMAGE_BASE}/ros2-tf:jazzy-ros-base-tf2.18.0
    TAGGED_IMAGE:   ${IMAGE}-v${CI_COMMIT_TAG}

manifest-ml:
  stage: Postprocessing
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - !reference [.docker-push-manifest, script]
  variables:
    IMAGE_CI_AMD64: ${IMAGE_BASE_CI}/ros2-ml:${CI_COMMIT_REF_SLUG}_jazzy-ros-base-tf2.18.0-torch2.5.0_ci-amd64
    IMAGE_CI_ARM64: ${IMAGE_BASE_CI}/ros2-ml:${CI_COMMIT_REF_SLUG}_jazzy-ros-base-tf2.18.0-torch2.5.0_ci-arm64
    IMAGE:          ${IMAGE_BASE}/ros2-ml:jazzy-ros-base-tf2.18.0-torch2.5.0
    TAGGED_IMAGE:   ${IMAGE}-v${CI_COMMIT_TAG}
